# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: dev-pipeline

on:
  push:
    branches: [ "development" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 8.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Lint Action
      uses: wearerequired/lint-action@v2.3.0
      with: 
        auto_fix: false
        dotnet_format: true
    - name: Build
      run: dotnet build --no-restore
  
  test:
    runs-on: ubuntu-latest
    steps:
    - name: Run unit tests
      run: dotnet test --no-build --verbosity normal

  deploy-master:
    runs-on: ubuntu-latest
    steps:
    - name: Create pull request
      uses: rematocorp/open-pull-request-action@v1
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        from-branch: development
        to-branch: master
        repository-owner: SabreDae
        repository: Assignment
    - name: Echo mergeable PR number
      run: echo ${{ steps.open_pr.outputs.pull_number }}
